#!/bin/sh

qmake -set PROPERTY_EDITOR_INSTALL_LIBS $PROJDIR/exaro-package/lib
qmake -set PROPERTY_EDITOR_INSTALL_HEADERS $PROJDIR/exaro-package/include
qmake -set PROPERTY_EDITOR_INSTALL_PLUGINS $PROJDIR/exaro-package/lib

cd lib
qmake && make -j2 && make install
cd ../plugins
qmake && make -j2 && make install
ldconfig
