git rm --cached ./app_new/Debug/moc_abstractrulebinder.obj
git rm --cached ./app_new/Debug/moc_abstracttableformat.obj
git rm --cached ./app_new/Debug/moc_buttongroup.obj
git rm --cached ./app_new/Debug/moc_custommsgbox.obj
git rm --cached ./app_new/Debug/moc_datemodel.obj
git rm --cached ./app_new/Debug/moc_dragdropmodel.obj
git rm --cached ./app_new/Debug/moc_fieldlistmodel.obj
git rm --cached ./app_new/Debug/moc_frameview.obj
git rm --cached ./app_new/Debug/moc_frmcatch.obj
git rm --cached ./app_new/Debug/moc_frmcell.obj
git rm --cached ./app_new/Debug/moc_frmchangereasons.obj
git rm --cached ./app_new/Debug/moc_frmexport.obj
git rm --cached ./app_new/Debug/moc_frmframe.obj
git rm --cached ./app_new/Debug/moc_frmframedetails.obj
git rm --cached ./app_new/Debug/moc_frmimport.obj
git rm --cached ./app_new/Debug/moc_frmimportregions.obj
git rm --cached ./app_new/Debug/moc_frmlegend.obj
git rm --cached ./app_new/Debug/moc_frmminorstrata.obj
git rm --cached ./app_new/Debug/moc_frmoperation.obj
git rm --cached ./app_new/Debug/moc_frmprjpage.obj
git rm --cached ./app_new/Debug/moc_frmregions.obj
git rm --cached ./app_new/Debug/moc_frmreports.obj
git rm --cached ./app_new/Debug/moc_frmsampling.obj
git rm --cached ./app_new/Debug/moc_frmtrip.obj
git rm --cached ./app_new/Debug/moc_frmvessel.obj
git rm --cached ./app_new/Debug/moc_frmvesseltype.obj
git rm --cached ./app_new/Debug/moc_generictab.obj
git rm --cached ./app_new/Debug/moc_login.obj
git rm --cached ./app_new/Debug/moc_mainfrm.obj
git rm --cached ./app_new/Debug/moc_mapperrulebinder.obj
git rm --cached ./app_new/Debug/moc_modelinterface.obj
git rm --cached ./app_new/Debug/moc_nullrelationaldelegate.obj
git rm --cached ./app_new/Debug/moc_previewtab.obj
git rm --cached ./app_new/Debug/moc_rulechecker.obj
git rm --cached ./app_new/Debug/moc_tableadapter.obj
git rm --cached ./app_new/Debug/moc_treemodel.obj
git rm --cached ./app_new/Debug/moc_xmltable.obj
git rm --cached ./app_new/GeneratedFiles/Debug/moc_abstractrulebinder.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_abstracttableformat.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_buttongroup.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_custommsgbox.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_datemodel.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_dragdropmodel.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_fieldlistmodel.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_frameview.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_frmcatch.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_frmcell.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_frmchangereasons.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_frmexport.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_frmframe.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_frmframedetails.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_frmimport.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_frmimportregions.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_frmlegend.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_frmminorstrata.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_frmoperation.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_frmprjpage.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_frmregions.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_frmreports.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_frmsampling.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_frmtrip.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_frmvessel.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_frmvesseltype.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_generictab.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_login.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_mainfrm.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_mapperrulebinder.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_modelinterface.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_nullrelationaldelegate.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_previewtab.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_rulechecker.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_tableadapter.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_treemodel.cpp
git rm --cached ./app_new/GeneratedFiles/Debug/moc_xmltable.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_abstractrulebinder.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_abstracttableformat.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_buttongroup.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_custommsgbox.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_datemodel.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_dragdropmodel.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_fieldlistmodel.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_frameview.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_frmcatch.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_frmcell.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_frmchangereasons.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_frmexport.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_frmframe.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_frmframedetails.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_frmimport.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_frmimportregions.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_frmlegend.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_frmminorstrata.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_frmoperation.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_frmprjpage.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_frmregions.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_frmreports.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_frmsampling.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_frmtrip.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_frmvessel.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_frmvesseltype.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_generictab.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_login.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_mainfrm.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_mapperrulebinder.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_modelinterface.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_nullrelationaldelegate.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_previewtab.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_rulechecker.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_tableadapter.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_treemodel.cpp
git rm --cached ./app_new/GeneratedFiles/release/moc_xmltable.cpp
git rm --cached ./app_new/Release/moc_abstractrulebinder.obj
git rm --cached ./app_new/Release/moc_abstracttableformat.obj
git rm --cached ./app_new/Release/moc_buttongroup.obj
git rm --cached ./app_new/Release/moc_custommsgbox.obj
git rm --cached ./app_new/Release/moc_datemodel.obj
git rm --cached ./app_new/Release/moc_dragdropmodel.obj
git rm --cached ./app_new/Release/moc_fieldlistmodel.obj
git rm --cached ./app_new/Release/moc_frameview.obj
git rm --cached ./app_new/Release/moc_frmcatch.obj
git rm --cached ./app_new/Release/moc_frmcell.obj
git rm --cached ./app_new/Release/moc_frmchangereasons.obj
git rm --cached ./app_new/Release/moc_frmconnect.obj
git rm --cached ./app_new/Release/moc_frmexport.obj
git rm --cached ./app_new/Release/moc_frmframe.obj
git rm --cached ./app_new/Release/moc_frmframedetails.obj
git rm --cached ./app_new/Release/moc_frmimport.obj
git rm --cached ./app_new/Release/moc_frmimportregions.obj
git rm --cached ./app_new/Release/moc_frmlegend.obj
git rm --cached ./app_new/Release/moc_frmminorstrata.obj
git rm --cached ./app_new/Release/moc_frmoperation.obj
git rm --cached ./app_new/Release/moc_frmprjpage.obj
git rm --cached ./app_new/Release/moc_frmregions.obj
git rm --cached ./app_new/Release/moc_frmreports.obj
git rm --cached ./app_new/Release/moc_frmsampling.obj
git rm --cached ./app_new/Release/moc_frmtrip.obj
git rm --cached ./app_new/Release/moc_frmvessel.obj
git rm --cached ./app_new/Release/moc_frmvesseltype.obj
git rm --cached ./app_new/Release/moc_generictab.obj
git rm --cached ./app_new/Release/moc_login.obj
git rm --cached ./app_new/Release/moc_mainfrm.obj
git rm --cached ./app_new/Release/moc_mapperrulebinder.obj
git rm --cached ./app_new/Release/moc_modelinterface.obj
git rm --cached ./app_new/Release/moc_nullrelationaldelegate.obj
git rm --cached ./app_new/Release/moc_previewtab.obj
git rm --cached ./app_new/Release/moc_rulechecker.obj
git rm --cached ./app_new/Release/moc_tableadapter.obj
git rm --cached ./app_new/Release/moc_treemodel.obj
git rm --cached ./app_new/Release/moc_xmltable.obj
git rm --cached ./conf_app/Debug/moc_booleantable.obj
git rm --cached ./conf_app/Debug/moc_conf_app.obj
git rm --cached ./conf_app/Debug/moc_frmlu.obj
git rm --cached ./conf_app/Debug/moc_frmtip.obj
git rm --cached ./conf_app/Debug/moc_login.obj
git rm --cached ./conf_app/Debug/moc_nullrelationaldelegate.obj
git rm --cached ./conf_app/GeneratedFiles/Debug/moc_booleantable.cpp
git rm --cached ./conf_app/GeneratedFiles/Debug/moc_conf_app.cpp
git rm --cached ./conf_app/GeneratedFiles/Debug/moc_frmlu.cpp
git rm --cached ./conf_app/GeneratedFiles/Debug/moc_frmtip.cpp
git rm --cached ./conf_app/GeneratedFiles/Debug/moc_login.cpp
git rm --cached ./conf_app/GeneratedFiles/Debug/moc_nullrelationaldelegate.cpp
git rm --cached ./conf_app/GeneratedFiles/Release/moc_booleantable.cpp
git rm --cached ./conf_app/GeneratedFiles/Release/moc_conf_app.cpp
git rm --cached ./conf_app/GeneratedFiles/Release/moc_frmtip.cpp
git rm --cached ./conf_app/GeneratedFiles/Release/moc_login.cpp
git rm --cached ./conf_app/GeneratedFiles/Release/moc_nullrelationaldelegate.cpp
git rm --cached ./conf_app/Release/moc_booleantable.obj
git rm --cached ./conf_app/Release/moc_conf_app.obj
git rm --cached ./conf_app/Release/moc_frmtip.obj
git rm --cached ./conf_app/Release/moc_login.obj
git rm --cached ./conf_app/Release/moc_nullrelationaldelegate.obj
